// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkzndfpozcfxdvxmavcv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdrem5kZnBvemNmeGR2eG1hdmN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc5NzcwNDUsImV4cCI6MjA1MzU1MzA0NX0.dt1OE-SG6cxyOP3A5sBzCkPamGB0xT1-Ysv8XX_RNOE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);